# Generated by Django 3.2.3 on 2021-07-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id  libro :')),
                ('nombre', models.CharField(max_length=99, verbose_name='Nombre del Libro :')),
                ('autor', models.CharField(max_length=99, verbose_name='Autor de libro :')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis de Libros')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio Libro :')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock de libro ')),
                ('publicacion', models.DateField(verbose_name=' Fecha de publicacion Libro :')),
            ],
        ),
    ]
