# Generated by Django 3.2.3 on 2021-07-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=99),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
