# Generated by Django 3.2.3 on 2021-07-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210703_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='sinopsis',
        ),
    ]
