# Generated by Django 3.2.3 on 2021-07-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210703_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(max_length=99, null=True, verbose_name='Autor de libro:'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id del  libro:'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=99, verbose_name='Nombre del Libro:'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio Libro:'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.DateField(null=True, verbose_name=' Fecha de publicacion Libro:'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(null=True, verbose_name='Sinopsis de Libros:'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock de libro: '),
        ),
    ]
